apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "frontend.fullname" . }}-frontend-0-tls
  labels:
  {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/alt-names: {{ join "," .Values.ingress.hosts }}
    cert-manager.io/certificate-name: frontend-0-tls
    cert-manager.io/common-name: {{ index .Values.ingress.hosts 0 }}
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: cert-manager-global
    cert-manager.io/uri-sans: ""