apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "frontend.fullname" . }}-frontend
  labels:
  {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}
