{{ if .Values.gcloudServiceKey.enabled }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "backend.fullname" . }}-gcloud-service-key
  labels:
  {{- include "backend.labels" . | nindent 4 }}
data:
  default_bucket: {{ required "gcloudServiceKey.defaultBucket is required" .Values.gcloudServiceKey.defaultBucket
    | b64enc | quote }}
  google_application_credentials: {{ required "gcloudServiceKey.googleApplicationCredentials is required" .Values.gcloudServiceKey.googleApplicationCredentials | b64enc |
    quote }}
  key.json: {{ required "gcloudServiceKey.keyJson is required" .Values.gcloudServiceKey.keyJson
    | b64enc | quote }}
  service_account: {{ required "gcloudServiceKey.serviceAccount is required" .Values.gcloudServiceKey.serviceAccount
    | b64enc | quote }}
type: Opaque
{{ end }}
