{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "backend.fullname" . }}-backend
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: {{ include "backend.listenerSetName" . }}
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- if and .Values.gateway.nginx.enabled .Values.gateway.nginx.internal.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /api/internal
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /internal
        - type: ExtensionRef
          extensionRef:
            group: gateway.nginx.org
            kind: SnippetsFilter
            name: {{ include "backend.fullname" . }}-backend-internal
      backendRefs:
        - name: {{ include "backend.fullname" . }}-backend
          port: {{ .Values.service.port }}
      {{- with .Values.gateway.timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    - matches:
        - path:
            type: PathPrefix
            value: /api
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: {{ include "backend.fullname" . }}-backend
          port: {{ .Values.service.port }}
      {{- with .Values.gateway.timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
