apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "backend.fullname" . }}-backend
  labels:
  {{- include "backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}
